### ISSUE TITLE
Bug: Crash on paper 1.19  (and 1.20)

### ISSUE THREAD

**Issue by njcuk9999** [Elikill58/UltimateHammer#8]
### Which platform are you using ?

Paper

### Versions of UltimateHammer and of the server

My version is: 2.1

### Step to reproduce

Just running the server. Possible that these paper versions are not supported but figured I'd give you the error anyway.

### Errors / Logs

[19:03:46 INFO]: [UltimateHammer] Enabling UltimateHammer v2.1
[19:03:46 ERROR]: Error occurred while enabling UltimateHammer v2.1 (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
        at com.elikill58.ultimatehammer.api.yaml.YamlConfiguration$1$1.<init>(YamlConfiguration.java:23) ~[UltimateHammer-2.1.jar:?]
        at com.elikill58.ultimatehammer.api.yaml.YamlConfiguration$1.initialValue(YamlConfiguration.java:23) ~[UltimateHammer-2.1.jar:?]
        at com.elikill58.ultimatehammer.api.yaml.YamlConfiguration$1.initialValue(YamlConfiguration.java:20) ~[UltimateHammer-2.1.jar:?]
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
        at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
        at com.elikill58.ultimatehammer.api.yaml.YamlConfiguration.load(YamlConfiguration.java:69) ~[UltimateHammer-2.1.jar:?]
        at com.elikill58.ultimatehammer.api.yaml.YamlConfiguration.load(YamlConfiguration.java:60) ~[UltimateHammer-2.1.jar:?]
        at com.elikill58.ultimatehammer.api.yaml.YamlConfiguration.load(YamlConfiguration.java:51) ~[UltimateHammer-2.1.jar:?]
        at com.elikill58.ultimatehammer.universal.utils.UniversalUtils.loadConfig(UniversalUtils.java:334) ~[UltimateHammer-2.1.jar:?]
        at com.elikill58.ultimatehammer.spigot.SpigotAdapter.<init>(SpigotAdapter.java:62) ~[UltimateHammer-2.1.jar:?]
        at com.elikill58.ultimatehammer.spigot.SpigotUltimateHammer.onEnable(SpigotUltimateHammer.java:47) ~[UltimateHammer-2.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-246]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-246]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-246]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:03:46 INFO]: [UltimateHammer] Disabling UltimateHammer v2.1

**Comment by Elikill58** [comment]
Can you come on discord and open a ticket ? I'll give you dev build. I didn't update the plugin yet...
